# @package _global_
config:
  MODEL:
    TRUNK:
      NAME: regnet
      REGNET:
        name: regnet_y_16gf
    HEAD:
      PARAMS: [
        ["swav_head", {"dims": [3024, 4096, 4096, 256], "use_bn": True, "num_clusters": []}],
      ]
    WEIGHTS_INIT:
      PARAMS_FILE: "manifold://ssl_framework/tree/checkpoints/f232070198/swav_ig1b_regnet16Gf_cosine_bs32_node16_sinkhorn10_proto16k_syncBN32_warmup2x/model_iteration244000.torch"
      STATE_DICT_KEY_NAME: classy_state_dict
