# @package _global_
config:
  MODEL:
    TRUNK:
      NAME: regnet
      REGNET:
        depth: 27
        w_0: 640
        w_a: 230.83
        w_m: 2.53
        group_width: 373
    HEAD:
      PARAMS: [
        ["swav_head", {"dims": [10444, 8192, 8192, 256], "use_bn": False, "num_clusters": []}],
      ]
