# @package _global_
engine_name: extract_label_predictions
config:
  TEST_ONLY: True
  TEST_MODEL: True
  METERS:
    name: accuracy_list_meter
    accuracy_list_meter:
      num_meters: 1
      topk_values: [1]
  DATA:
    NUM_DATALOADER_WORKERS: 5
    TEST:
      DATA_SOURCES: [disk_filelist]
      LABEL_SOURCES: []
      LABEL_TYPE: sample_index
      DATASET_NAMES: [im2gps_3k_test_filelist]
      BATCHSIZE_PER_REPLICA: 32
      TRANSFORMS:
        - name: Resize
          size: 224
        - name: CenterCrop
          size: 224
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
      MMAP_MODE: False
  MODEL:
    TRUNK:
      NAME: resnet
      TRUNK_PARAMS:
        RESNETS:
          DEPTH: 50
    WEIGHTS_INIT:
      PARAMS_FILE: "specify the model weights"
      STATE_DICT_KEY_NAME: classy_state_dict
  DISTRIBUTED:
    NUM_NODES: 1
    NUM_PROC_PER_NODE: 1
  MACHINE:
    DEVICE: gpu
  GEO_LOCALIZATION:
    TRAIN_LABEL_MAPPING: "manifold://ssl_framework/tree/datasets/im2gps_parsed_data/mp16_places365_mapping_h3.json"
    ACC_KM_THRESHOLDS: [1, 25, 200, 750, 2500]
