# @package _global_
config:
  METERS:
    name: accuracy_list_meter
    accuracy_list_meter:
      num_meters: 5
      topk_values: [1, 5]
  MODEL:
    FEATURE_EVAL_SETTINGS:
      LINEAR_EVAL_FEAT_POOL_OPS_MAP: [
        ["res4", ["AdaptiveAvgPool2d", [[3, 3]]]],
        ["res5", ["AdaptiveAvgPool2d", [[4, 1]]]],
        ["avgpool", ["Identity", []]],
        ["avgpool", ["Identity", []]],
      ]
    TRUNK:
      NAME: regnet
      REGNET:
        name: regnet_y_16gf
    HEAD:
      PARAMS: [
        ["eval_mlp", {"in_channels": 1232, "dims": [11088, 397]}],
        ["eval_mlp", {"in_channels": 3024, "dims": [12096, 397]}],
        ["eval_mlp", {"in_channels": 3024, "dims": [3024, 397]}],
        ["mlp", {"dims": [3024, 397]}],
      ]
