# @package _global_
config:
  MODEL:
    FEATURE_EVAL_SETTINGS:
      LINEAR_EVAL_FEAT_POOL_OPS_MAP: [
        ["res4", ["AdaptiveAvgPool2d", [[3, 3]]]],
        ["res5", ["AdaptiveAvgPool2d", [[4, 1]]]],
        ["avgpool", ["Identity", []]],
      ]
    TRUNK:
      NAME: regnet
      REGNET:
        name: regnet_y_16gf
    HEAD:
      PARAMS: [
        ["eval_mlp", {"in_channels": 1232, "dims": [11088, 2]}],
        ["eval_mlp", {"in_channels": 3024, "dims": [12096, 2]}],
        ["eval_mlp", {"in_channels": 3024, "dims": [3024, 2]}],
      ]
