MODEL:
  MASK_ON: True
  PIXEL_STD: [57.375, 57.120, 58.395]
  REGNET:
    DEPTH: 25
    W0: 88
    WA: 26.31
    WM: 2.25
    GROUP_W: 48
    SE_R: 0.0  # RegNetX
    NORM: "SyncBN"
  BACKBONE:
    FREEZE_AT: 0
    NAME: "build_regnet_backbone"
  META_ARCHITECTURE: "GeneralizedRCNN"
  RPN:
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: "Res5ROIHeadsExtraNorm"
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  WARMUP_ITERS: 50
TEST:
  PRECISE_BN:
    ENABLED: True
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
VERSION: 2
