# @package _global_
config:
  DATA:
    TRAIN:
      TRANSFORMS:
        - name: Resize
          size: 256
        - name: RandomCrop
          size: 227
        - name: RandomHorizontalFlip
        - name: ImgToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
    TEST:
      TRANSFORMS:
        - name: Resize
          size: [256, 256]
        - name: CenterCrop
          size: 227
        - name: ImgToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
  MODEL:
    TRUNK:
      NAME: alexnet_jigsaw
      LINEAR_FEAT_POOL_OPS: [
          ["AvgPool2d", [[28, 28], 9, 0]],
          ["AvgPool2d", [[24, 24], 6, 0]],
          ["AvgPool2d", [[14, 14], 3, 0]],
          ["AvgPool2d", [[14, 14], 3, 0]],
          ["AvgPool2d", [[16, 16], 2, 0]],
      ]
    HEAD:
      PARAMS: [["mlp", {"dims": [9216, 20]}]]
