# @package _global_
config:
  MODEL:
    TRUNK:
      NAME: resnet
      ######## resnext101-32x8d #######
      RESNETS:
        DEPTH: 101
        GROUPS: 32
        WIDTH_PER_GROUP: 8
    HEAD:
      PARAMS: [['mlp', {'dims': [2048, 1000]}]]
    SYNC_BN_CONFIG:
      CONVERT_BN_TO_SYNC_BN: True
      SYNC_BN_TYPE: apex
      GROUP_SIZE: 8
  DISTRIBUTED:
    NUM_NODES: 2  # we can't fit the model on 16GB machine so instead use 2 nodes
    INIT_METHOD: tcp
