# @package _global_
config:
  VERBOSE: False
  LOG_FREQUENCY: 100
  TEST_ONLY: False
  TEST_MODEL: False
  SEED_VALUE: 0
  MULTI_PROCESSING_METHOD: forkserver
  MONITOR_PERF_STATS: False
  DATA:
    TRAIN:
      DATA_SOURCES: [disk_filelist]
      DATASET_NAMES: [imagenet1k]
      BATCHSIZE_PER_REPLICA: 32
      LABEL_TYPE: sample_index
      TRANSFORMS:
        - name: ColorJitter
          brightness: 0.4
          contrast: 0.4
          saturation: 0.4
          hue: 0.4
        - name: RandomResizedCrop
          size: 224
        - name: RandomHorizontalFlip
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
      MMAP_MODE: True
      COPY_TO_LOCAL_DISK: True
      COPY_DESTINATION_DIR: /tmp/imagenet1k/
  TRAINER:
    TRAIN_STEP_NAME: standard
  METERS: null
  MODEL:
    TRUNK:
      NAME: resnet
      TRUNK_PARAMS:
        RESNETS:
          DEPTH: 50
    HEAD:
      PARAMS: [["mlp", {"dims": [2048, 128]}]]
  CRITERION:
      name: nce_loss_with_memory
      ignore_index: -1
      NCE_LOSS:
        NORM_EMBEDDING: True
        TEMPERATURE: 0.07
        NORM_CONSTANT: -1
        NEGATIVE_SAMPLING_PARAMS:
          NUM_NEGATIVES: 4096
          TYPE: random
        MEMORY_PARAMS:
          MEMORY_SIZE: -1
          EMBEDDING_DIM: 128
          MOMENTUM: 0.5
          NORM_INIT: True
          UPDATE_MEM_ON_FORWARD: True
  OPTIMIZER:
      name: sgd
      weight_decay: 0.0001
      momentum: 0.9
      num_epochs: 200
      nesterov: False
      regularize_bn: False
      regularize_bias: True
      param_schedulers:
        lr:
          base_value: 0.03   # LR for batch size 256
          name: multistep
          values: [0.03, 0.003, 0.0003]
          milestones: [120, 160]
          update_interval: epoch
  DISTRIBUTED:
    BACKEND: nccl
    NUM_NODES: 1
    NUM_PROC_PER_NODE: 8
    INIT_METHOD: tcp
    RUN_ID: auto
  MACHINE:
    NUM_DATALOADER_WORKERS: 5
    DEVICE: gpu
  CHECKPOINT:
    DIR: "."
    AUTO_RESUME: True
    CHECKPOINT_FREQUENCY: 10
