# @package _global_
config:
  MODEL:
    TRUNK:
      NAME: regnet
      TRUNK_PARAMS:
        REGNET:
          name: regnet_y_256gf
    HEAD:
      PARAMS: [
        ["mlp", {"dims": [5088, 5088], "use_relu": True}],
        ["mlp", {"dims": [5088, 128], "use_relu": False}],
      ]
