# @package _global_
config:
  MODEL:
    TRUNK:
      NAME: regnet
      TRUNK_PARAMS:
        REGNET:
          name: regnet_y_3.2gf
    HEAD:
      PARAMS: [
        ["mlp", {"dims": [1512, 1512], "use_relu": True}],
        ["mlp", {"dims": [1512, 128], "use_relu": False}],
      ]
