# @package _global_
config:
  MODEL:
    TRUNK:
      NAME: resnet
      TRUNK_PARAMS:
        RESNETS:
          DEPTH: 50
          ######## resnext50-32x4d #######
          # GROUPS: 32
          # WIDTH_PER_GROUP: 4
          ######## resnext50-32x8d #######
          # GROUPS: 32
          # WIDTH_PER_GROUP: 8
          ######## resnext50-32x16d #######
          # GROUPS: 32
          # WIDTH_PER_GROUP: 16
          ######## resnext50-32x32d #######
          # GROUPS: 32
          # WIDTH_PER_GROUP: 32
          ######## resnext50-32x48d #######
          # GROUPS: 32
          # WIDTH_PER_GROUP: 48
    HEAD:
      # setting 1
      PARAMS: [
        ["mlp", {"dims": [2048, 2048], "use_relu": True, "use_bn": True, "use_bias": False}],
        ["mlp", {"dims": [2048, 128], "use_relu": False, "use_bn": False, "use_bias": False}],
      ]
    # HEAD:
    #   # setting 2
    #   PARAMS: [
    #     ["mlp", {"dims": [2048, 2048], "use_relu": True, "use_bn": True, "use_bias": False}],
    #     ["mlp", {"dims": [2048, 128], "use_relu": False, "use_bn": True, "use_bias": False}],
    #   ]
    # NON_TRAINABLE_PARAMS: ["heads.1.clf.1.bias"]  # corresponds to the BN of the last BN layer
