# @package _global_
config:
  MODEL:
    TRUNK:
      NAME: resnet
      RESNETS:
        DEPTH: 50
        WIDTH_MULTIPLIER: 3
    HEAD:
      PARAMS: [
        ["mlp", {"dims": [6144, 6144], "use_relu": True, "skip_last_layer_relu_bn": False}],
        ["mlp", {"dims": [6144, 128]}],
      ]
