# @package _global_
config:
  DATA:
    TRAIN:
      DROP_LAST: True
      TRANSFORMS:
        - name: RandomResizedCrop
          size: 384
          interpolation: 3
        - name: RandomHorizontalFlip
        - name: RandAugment
          magnitude: 9
          magnitude_std: 0.5
          increasing_severity: True
        - name: ColorJitter
          brightness: 0.4
          contrast: 0.4
          saturation: 0.4
          hue: 0.4
        - name: RandomGrayscale
          p: 0.2
        - name: ToTensor
        - name: RandomErasing
          p: 0.25
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
      COLLATE_FUNCTION: cutmixup_collator
      COLLATE_FUNCTION_PARAMS: {
        "mixup_alpha": 0.1,
        "cutmix_alpha": 0.0,
        "num_classes": 1000
      }
    TEST:
      TRANSFORMS:
        - name: Resize
          size: 384
          interpolation: 3
        - name: CenterCrop
          size: 384
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
