# @package _global_
config:
  DATA:
    TRAIN:
      BATCHSIZE_PER_REPLICA: 16
    TEST:
      BATCHSIZE_PER_REPLICA: 16
  MODEL:
    TRUNK:
      NAME: regnet
      REGNET:
        name: regnet_y_128gf
    HEAD:
      PARAMS: [
        ["swav_head", {"normalize_feats": False, "skip_last_bn": False, "use_bn": True, "dims": [7392, 8192], "num_clusters": []}],
        ['mlp', {'dims': [8192, 8142]}]
      ]
      # PARAMS: [['mlp', {'dims': [7392, 1000]}]]
  DISTRIBUTED:
    NUM_NODES: 2  # we can't fit the model on 16GB machine so instead use 2 nodes
    INIT_METHOD: tcp
