# @package _global_
config:
  METERS:
    name: accuracy_list_meter
    accuracy_list_meter:
      num_meters: 3
      topk_values: [1]
  MODEL:
    FEATURE_EVAL_SETTINGS:
      LINEAR_EVAL_FEAT_POOL_OPS_MAP: [
        ["res4", ["AdaptiveAvgPool2d", [[7, 1]]]],
        ["res5", ["AdaptiveAvgPool2d", [[3, 1]]]],
        ["avgpool", ["Identity", []]],
      ]
    TRUNK:
      NAME: regnet
      REGNET:
        name: regnet_y_32gf
    HEAD:
      PARAMS: [
        ["eval_mlp", {"in_channels": 1392, "dims": [9744, 43]}],
        ["eval_mlp", {"in_channels": 3712, "dims": [11136, 43]}],
        ["eval_mlp", {"in_channels": 3712, "dims": [3712, 43]}],
      ]
