# @package _global_
config:
  MODEL:
    FEATURE_EVAL_SETTINGS:
      EVAL_MODE_ON: True
      FREEZE_TRUNK_ONLY: True
      EXTRACT_TRUNK_FEATURES_ONLY: True
      SHOULD_FLATTEN_FEATS: False
      LINEAR_EVAL_FEAT_POOL_OPS_MAP: [
        ["res4", ["Identity", []]],
        ["res5", ["Identity", []]],
        ["res5avg", ["Identity", []]],
      ]
    TRUNK:
      NAME: resnet
      RESNETS:
        DEPTH: 50
        ######## resnext50-32x4d #######
        # GROUPS: 32
        # WIDTH_PER_GROUP: 4
        ######## resnext50-32x8d #######
        # GROUPS: 32
        # WIDTH_PER_GROUP: 8
        ######## resnext50-32x16d #######
        # GROUPS: 32
        # WIDTH_PER_GROUP: 16
