# @package _global_
config:
  METERS:
    name: accuracy_list_meter
    accuracy_list_meter:
      num_meters: 2
      topk_values: [5]
  MODEL:
    FEATURE_EVAL_SETTINGS:
      LINEAR_EVAL_FEAT_POOL_OPS_MAP: [
        ["res5", ["AdaptiveAvgPool2d", [[1, 2]]]],
        ["avgpool", ["Identity", []]],
      ]
    TRUNK:
      NAME: regnet
      TRUNK_PARAMS:
        REGNET:
          name: regnet_y_128gf
    HEAD:
      PARAMS: [
        ["eval_mlp", {"in_channels": 7392, "dims": [14784, 1000]}],
        ["mlp", {"dims": [7392, 1000]}],
      ]
