# @package _global_
config:
  METERS:
    accuracy_list:
      num_list: 1
      topk: [1, 5]
  MODEL:
    EVAL_FEATURES: ["res5"]
    TRUNK:
      NAME: regnet
      TRUNK_PARAMS:
        REGNET:
          name: regnet_y_3.2gf
      LINEAR_FEAT_POOL_OPS: [
          ["AvgPool2d", [[3, 3], 2, 0]],
      ]
    HEAD:
      PARAMS: [
        ["eval_mlp", {"in_channels": 1512, "dims": [9792, 1000]}],
      ]
