# @package _global_
config:
  METERS:
    accuracy_list:
      num_list: 1
      topk: [1, 5]
  MODEL:
    EVAL_FEATURES: ["res5"]
    TRUNK:
      NAME: regnet
      TRUNK_PARAMS:
        REGNET:
          name: regnet_y_1.6gf
      LINEAR_FEAT_POOL_OPS: [
          ["AdaptiveAvgPool2d", [[4, 3]]],
      ]
    HEAD:
      PARAMS: [
        ["eval_mlp", {"in_channels": 888, "dims": [10656, 1000]}],
      ]
