# @package _global_
config:
  TEST_MODEL: True
  TEST_ONLY: True
  DATA:
    TEST:
      TRANSFORMS:
        - name: Resize
          size: [224, 224]
        - name: CenterCrop
          size: 224
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
