# @package _global_
config:
  DATA:
    TRAIN:
      TRANSFORMS:
        - name: Resize
          size: 256
        - name: RandomCrop
          size: 227
        - name: RandomHorizontalFlip
        - name: ImgPil2LabTensor
    TEST:
      TRANSFORMS:
        - name: Resize
          size: 256
        - name: CenterCrop
          size: 227
        - name: ImgPil2LabTensor
  MODEL:
    INPUT_TYPE: lab
    FEATURE_EVAL_SETTINGS:
      LINEAR_EVAL_FEAT_POOL_OPS_MAP: [
          ["conv1", ["AvgPool2d", [[19, 19], 4, 0]]],
          ["conv2", ["AvgPool2d", [[12, 12], 3, 0]]],
          ["conv3", ["AvgPool2d", [[9, 9], 1, 0]]],
          ["conv4", ["AvgPool2d", [[9, 9], 1, 0]]],
          ["conv5", ["AvgPool2d", [[8, 8], 1, 0]]],
      ]
    TRUNK:
      NAME: alexnet_colorization
    HEAD:
      PARAMS: [
        ["eval_mlp", {"in_channels": 96, "dims": [9600, 1000]}],
        ["eval_mlp", {"in_channels": 256, "dims": [9216, 1000]}],
        ["eval_mlp", {"in_channels": 384, "dims": [9600, 1000]}],
        ["eval_mlp", {"in_channels": 384, "dims": [9600, 1000]}],
        ["eval_mlp", {"in_channels": 256, "dims": [9216, 1000]}],
      ]
  OPTIMIZER:
    nesterov: True
    regularize_bn: False
    regularize_bias: False
