# @package _global_
config:
  HOOKS:
    PERF_STATS:
      MONITOR_PERF_STATS: True
  CHECKPOINT:
    DIR: "."
    AUTO_RESUME: True
    CHECKPOINT_FREQUENCY: 5
  DATA:
    NUM_DATALOADER_WORKERS: 5
    TRAIN:
      MMAP_MODE: true
      DATA_SOURCES: [disk_filelist]
      LABEL_SOURCES: [disk_filelist]
      DATASET_NAMES: [patch_camelyon_filelist]
      BATCHSIZE_PER_REPLICA: 32
      TRANSFORMS:
        - name: RandomResizedCrop
          size: 224
        - name: RandomHorizontalFlip
        - name: ColorJitter
          brightness: 0.4
          contrast: 0.4
          saturation: 0.4
          hue: 0.4
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
    TEST:
      MMAP_MODE: true
      COPY_DESTINATION_DIR: /tmp/patch_camelyon/
      COPY_TO_LOCAL_DISK: false
      DATA_SOURCES: [disk_filelist]
      LABEL_SOURCES: [disk_filelist]
      DATASET_NAMES: [patch_camelyon_filelist]
      BATCHSIZE_PER_REPLICA: 32
      TRANSFORMS:
        - name: Resize
          size: 224
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
  MODEL:
    TRUNK:
      NAME: resnet
      RESNETS:
        DEPTH: 50
    HEAD:
      PARAMS: [
        ["mlp", {"dims": [2048, 2]}],
      ]
  LOSS:
    name: cross_entropy_multiple_output_single_target
    cross_entropy_multiple_output_single_target:
      ignore_index: -1
  OPTIMIZER:
    name: sgd
    weight_decay: 0.0005
    momentum: 0.9
    num_epochs: 105
    nesterov: True
    regularize_bn: False
    regularize_bias: True
    param_schedulers:
      lr:
        auto_lr_scaling:
          auto_scale: true
          base_value: 0.01
          base_lr_batch_size: 256
        milestones: [30, 60, 90] # epochs at which to drop the learning rate (N vals)
        values: [0.01, 0.001, 0.0001, 0.00001] # the exact values of learning rate (N+1 vals)
        name: multistep
        update_interval: epoch
  METERS:
    name: accuracy_list_meter
    accuracy_list_meter:
      num_meters: 1
      topk_values: [1]
  TRAINER:
    TRAIN_STEP_NAME: standard_train_step
  DISTRIBUTED:
    BACKEND: nccl
    INIT_METHOD: tcp
    NUM_NODES: 1
    NUM_PROC_PER_NODE: 8 # 8 GPUs
    RUN_ID: auto
  MACHINE:
    DEVICE: gpu
  VERBOSE: True
  LOG_FREQUENCY: 200
  TEST_ONLY: False
  TEST_EVERY_NUM_EPOCH: 1
  TEST_MODEL: True
  SEED_VALUE: 0
  MULTI_PROCESSING_METHOD: forkserver
