package:
  name: vissl
  version: "{{ environ.get('BUILD_VERSION') }}"

source:
 path: ../../../..

requirements:

  host:
    - python
    - setuptools

  run:
    - python
    - pytorch
    - apex
    - torchvision>=0.5
    - scipy
    - scikit-learn
    - parameterized
    - numpy >=1.11
    - faiss-gpu
    - fvcore
    - iopath
    - importlib_resources
    - hydra-core
    - tabulate

test:
  imports:
    - torch
    - torch.cuda
    - vissl
    - apex
    - tensorboard
    - hydra
  source_files:
    - tests
    - tools
    - dev/run_quick_tests.sh
    - configs
  requires:
    - ca-certificates
    - cudatoolkit=10.1
    - opencv
    - tensorboard
  commands:
    - python -m unittest discover -v -s tests
    - ./dev/run_quick_tests.sh

build:
  string: py{{py}}
  script: python setup.py install --single-version-externally-managed --record=record.txt # [not win]

about:
  home: https://github.com/facebookresearch/vissl
  license: MIT
  license_file: LICENSE
  summary: computer VIsion library for state-of-the-art Self-Supervised Learning research with PyTorch
