package:
  name: vissl
  version: "{{ environ.get('BUILD_VERSION') }}"

source:
 path: ../../../..

requirements:

  host:
    - python
    - setuptools

  run:
    - python
    - pytorch
    - torchvision
    - apex

build:
  string: py{{py}}
  script: python setup.py install --single-version-externally-managed --record=record.txt # [not win]

about:
  home: https://github.com/facebookresearch/vissl
  license: CC-NC 4.0 International
  license_file: LICENSE
  summary: computer VIsion library for state-of-the-art Self-Supervised Learning research with PyTorch