# @package _global_
config:
  TEST_ONLY: True
  METERS:
    name: accuracy_list_meter
    accuracy_list_meter:
      topk_values: [1, 5]
  MODEL:
    FEATURE_EVAL_SETTINGS:
      EXTRACT_TRUNK_FEATURES_ONLY: False
      EVAL_MODE_ON: True
      FREEZE_TRUNK_AND_HEAD: True
      FREEZE_TRUNK_ONLY: False
      EVAL_TRUNK_AND_HEAD: True
      SHOULD_FLATTEN_FEATS: False
  LOSS:
    name: cross_entropy_multiple_output_single_target