# @package _global_
config:
  METERS:
    name: accuracy_list_meter
    accuracy_list_meter:
      topk_values: [1, 5]
  MODEL:
    FEATURE_EVAL_SETTINGS:
      EVAL_MODE_ON: True
      FREEZE_TRUNK_ONLY: True
      SHOULD_FLATTEN_FEATS: False
  LOSS:
    name: cross_entropy_multiple_output_single_target
  OPTIMIZER:
    name: sgd
    weight_decay: 0.0005
    momentum: 0.9
    num_epochs: 100
    nesterov: True
    regularize_bn: True
    regularize_bias: True
    param_schedulers:
      lr:
        auto_lr_scaling:
          auto_scale: true
          base_value: 0.01
          base_lr_batch_size: 256
        name: multistep
        values: [0.01, 0.001, 0.0001, 0.00001]
        milestones: [28, 56, 84]
        update_interval: epoch