 # @package _global_
 config:
  MODEL:
    FEATURE_EVAL_SETTINGS:
      LINEAR_EVAL_FEAT_POOL_OPS_MAP: [
        ["res4", ["AvgPool2d", [[8, 8], 3, 0]]],
        ["res5", ["AvgPool2d", [[6, 6], 1, 0]]],
        ["res5", ["AdaptiveAvgPool2d", [[2, 2]]]],
        ["res5avg", ["Identity", []]],
      ]
    TRUNK:
      NAME: resnet
      RESNETS:
        DEPTH: 50
        ######## resnext50-32x4d #######
        # GROUPS: 32
        # WIDTH_PER_GROUP: 4
        ######## resnext50-32x8d #######
        # GROUPS: 32
        # WIDTH_PER_GROUP: 8
        ######## resnext50-32x16d #######
        # GROUPS: 32
        # WIDTH_PER_GROUP: 16
    HEAD:
      PARAMS: [
        ["eval_mlp", {"in_channels": 1024, "dims": [9216, 45]}],
        ["eval_mlp", {"in_channels": 2048, "dims": [8192, 45]}],
        ["eval_mlp", {"in_channels": 2048, "dims": [8192, 45]}],
        ["eval_mlp", {"in_channels": 2048, "dims": [2048, 45]}],
      ]
