# @package _global_
config:
  VERBOSE: False
  LOG_FREQUENCY: 2
  TEST_ONLY: False
  TEST_MODEL: False
  SEED_VALUE: 0
  MULTI_PROCESSING_METHOD: forkserver
  MONITOR_PERF_STATS: True
  PERF_STAT_FREQUENCY: 40
  ROLLING_BTIME_FREQ: 5
  DATA:
    TRAIN:
      DATA_SOURCES: [disk]
      DATASET_NAMES: [imagenet1k]
      BATCHSIZE_PER_REPLICA: 32
      LABEL_TYPE: sample_index    # just an implementation detail. Label isn't used
      TRANSFORMS:
        - name: ImgPilToMultiCrop
          total_nmb_crops: 2
          size_crops: [224]
          nmb_crops: [2]
          crop_scales: [[0.14, 1]]
        - name: RandomHorizontalFlip
          p: 0.5
        - name: ImgPilColorDistortion
          strength: 1.0
        - name: ImgPilGaussianBlur
          kernel: 23
          p: 0.5
          radius_min: 0.1
          radius_max: 2.0
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
      COLLATE_FUNCTION: multires_collator
      MMAP_MODE: True
      COPY_TO_LOCAL_DISK: False
      COPY_DESTINATION_DIR: /tmp/imagenet1k/
      DATA_LIMIT: 500
      DROP_LAST: True
  TRAINER:
    TRAIN_STEP_NAME: standard
  METERS: null
  MODEL:
    TRUNK:
      NAME: resnet
      RESNETS:
        DEPTH: 50
    HEAD:
      PARAMS: [
        ["mlp", {"dims": [2048, 2048], "use_relu": True}],
        ["mlp", {"dims": [2048, 128]}],
      ]
    TEMP_FROZEN_PARAMS_ITER_MAP: []
    SYNC_BN_CONFIG:
      CONVERT_BN_TO_SYNC_BN: True
      SYNC_BN_TYPE: pytorch
  CRITERION:
    name: deepclusterv2_loss
    NUM_TRAIN_SAMPLES: 500
    #NUM_TRAIN_SAMPLES: 1281167
    DEEPCLUSTERV2_LOSS:
      BATCHSIZE_PER_REPLICA: 64
      NMB_CROPS: 2
      TEMPERATURE: 0.1
      NMB_CLUSTERS: [10, 10, 10]
      KMEANS_ITERS: 10
      MEMORY_PARAMS:
        CROPS_FOR_MB: [0, 1]
        EMBEDDING_DIM: 128
  OPTIMIZER:
      name: sgd
      use_larc: True
      larc_config:
        clip: False
        trust_coefficient: 0.001
        eps: 0.00000001
      weight_decay: 0.000001
      momentum: 0.9
      nesterov: False
      num_epochs: 1
      regularize_bn: True
      regularize_bias: True
      param_schedulers:
        lr:
          name: cosine
          start_value: 0.15   # LR for batch size 256
          end_value: 0.0000
          update_interval: step
  DISTRIBUTED:
    DISTR_ON: True
    BACKEND: nccl
    NUM_NODES: 1
    NUM_PROC_PER_NODE: 2
    INIT_METHOD: tcp
    RUN_ID: auto
  MACHINE:
    NUM_DATALOADER_WORKERS: 5
    DEVICE: gpu
  CHECKPOINT:
    DIR: "."
    AUTO_RESUME: True
    CHECKPOINT_FREQUENCY: 5
    OVERWRITE_EXISTING: true
