# @package _global_
config:
  CHECKPOINT:
    DIR: "checkpoints"
    AUTO_RESUME: True
    CHECKPOINT_FREQUENCY: 1
  DATA:
    TRAIN:
      DATA_SOURCES: [disk_folder]
      DATA_PATHS: ["<path to train folder>"]
      LABEL_SOURCES: [disk_folder]
      DATASET_NAMES: [imagenet1k]
      BATCHSIZE_PER_REPLICA: 64
      TRANSFORMS:
        - name: RandomResizedCrop
          size: 224
        - name: RandomHorizontalFlip
        - name: ColorJitter
          brightness: 0.4
          contrast: 0.4
          saturation: 0.4
          hue: 0.4
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
    TEST:
      DATA_SOURCES: [disk_folder]
      DATA_PATHS: ["<path to train folder>"]
      LABEL_SOURCES: [disk_folder]
      DATASET_NAMES: [imagenet1k]
      BATCHSIZE_PER_REPLICA: 64
      TRANSFORMS:
        - name: Resize
          size: 256
        - name: CenterCrop
          size: 224
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
  MODEL:
    TRUNK:
      NAME: resnet
      TRUNK_PARAMS:
        RESNETS:
          DEPTH: 50
    HEAD:
      PARAMS: [
        ["mlp", {"dims": [2048, 1000]}],
      ]
  CRITERION:
      name: cross_entropy_multiple_output_single_target
      ignore_index: -1
  OPTIMIZER:
      name: sgd
      weight_decay: 0.0001
      momentum: 0.9
      num_epochs: 105
      nesterov: True
      regularize_bn: False
      regularize_bias: True
      param_schedulers:
        lr:
          base_value: 0.025 # this learning rate is for an effective batch size of 64
          name: multistep
          # We want the learning rate to drop by 1/10
          # at epochs [30, 60, 90, 100]
          milestones: [30, 60, 90, 100] # epochs at which to drop the learning rate (N vals)
          values: [0.025, 0.0025, 0.00025, 0.000025, 0.0000025] # the exact values of learning rate (N+1 vals)
          update_interval: epoch
  METERS:
    accuracy_list:
      num_list: 1
      topk: [1, 5]
  TRAINER:
    TRAIN_STEP_NAME: standard
  DISTRIBUTED:
    BACKEND: nccl
    NUM_NODES: 1
    NUM_PROC_PER_NODE: 1 # 1 GPU
    RUN_ID: auto
  MACHINE:
    NUM_DATALOADER_WORKERS: 5
    DEVICE: gpu
  VERBOSE: True
  LOG_FREQUENCY: 100
  TEST_ONLY: False
  TEST_EVERY_NUM_EPOCH: 1
  TEST_MODEL: True
  SEED_VALUE: 0
  MULTI_PROCESSING_METHOD: fork
