# @package _global_
config:
  METERS:
    accuracy_list_meter:
      meter_names: ["cls1_mlp"]
  MODEL:
    FEATURE_EVAL_SETTINGS:
      EXTRACT_TRUNK_FEATURES_ONLY: False
      SHOULD_FLATTEN_FEATS: False
    HEAD:
      PARAMS: [
        ["mlp", {"dims" : [768, 1000]}]
      ]