# @package _global_
config:
  MODEL:
    TRUNK:
      NAME: resnet
      RESNETS:
        DEPTH: 50
        WIDTH_MULTIPLIER: 4
    HEAD:
      PARAMS: [
        ["mlp", {"dims": [8192, 8192], "use_relu": True, "skip_last_layer_relu_bn": False}],
        ["mlp", {"dims": [8192, 128]}],
      ]
