# @package _global_
config:
  METERS:
    name: accuracy_list_meter
    accuracy_list_meter:
      num_meters: 5
      topk_values: [1, 5]
  MODEL:
    FEATURE_EVAL_SETTINGS:
      LINEAR_EVAL_FEAT_POOL_OPS_MAP: [
        ["res4", ["AdaptiveAvgPool2d", [[2, 1]]]],
        ["res4", ["AdaptiveAvgPool2d", [[1, 2]]]],
        ["res4", ["AdaptiveAvgPool2d", [[3, 1]]]],

        ["res5", ["AdaptiveAvgPool2d", [[2, 1]]]],
        ["res5", ["AdaptiveAvgPool2d", [[1, 2]]]],

        ["avgpool", ["Identity", []]],
        ["avgpool", ["Identity", []]],
      ]
    TRUNK:
      NAME: regnet
      REGNET:
        depth: 27
        w_0: 640
        w_a: 230.83
        w_m: 2.53
        group_width: 373
    HEAD:
      PARAMS: [
        ["eval_mlp", {"in_channels": 4103, "dims": [8206, 182]}],
        ["eval_mlp", {"in_channels": 4103, "dims": [8206, 182]}],
        ["eval_mlp", {"in_channels": 4103, "dims": [12309, 182]}],

        ["eval_mlp", {"in_channels": 10444, "dims": [20888, 182]}],
        ["eval_mlp", {"in_channels": 10444, "dims": [20888, 182]}],

        ["eval_mlp", {"in_channels": 10444, "dims": [10444, 182]}],
        ["mlp", {"dims": [10444, 182]}],
      ]
