# @package _global_
config:
  DATA:
    TRAIN:
      TRANSFORMS:
        - name: Resize
          size: 438
        - name: RandomHorizontalFlip
        - name: CenterCrop
          size: 384
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
    TEST:
      TRANSFORMS:
        - name: Resize
          size: 438
        - name: CenterCrop
          size: 384
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
