# @package _global_
config:
  MODEL:
    TRUNK:
      NAME: regnet
      TRUNK_PARAMS:
        REGNET:
          name: regnet_y_3.2gf
    HEAD:
      PARAMS: [
        ["swav_head", {"dims": [1512, 1512, 128], "use_bn": True, "nmb_clusters": [3000]}],
      ]
