# @package _global_
config:
  MODEL:
    TRUNK:
      NAME: regnet
      TRUNK_PARAMS:
        REGNET:
          name: regnet_y_1.6gf
    HEAD:
      PARAMS: [
        ["swav_head", {"dims": [888, 888, 128], "use_bn": True, "nmb_clusters": [3000]}],
      ]
