# @package _global_
config:
  MODEL:
    FEATURE_EVAL_SETTINGS:
      EVAL_MODE_ON: True
      FREEZE_TRUNK_AND_HEAD: True
      EVAL_TRUNK_AND_HEAD: True
    TRUNK:
      NAME: regnet
      REGNET:
        depth: 27
        w_0: 640
        w_a: 230.83
        w_m: 2.53
        group_width: 373
    HEAD:
      PARAMS: [
        ["swav_head", {"dims": [10444, 8192, 8192, 256], "use_bn": False, "num_clusters": []}],
      ]
    WEIGHTS_INIT:
      STATE_DICT_KEY_NAME: classy_state_dict
      SKIP_LAYERS: ["num_batches_tracked"]
