# @package _global_
config:
  MODEL:
    TRUNK:
      NAME: regnet
      REGNET:
        name: regnet_y_16gf
    HEAD:
      PARAMS: [
        ["swav_head", {"dims": [3024, 3024, 128], "use_bn": False, "num_clusters": []}],
      ]
