# @package _global_
config:
  MODEL:
    TRUNK:
      NAME: resnet
      TRUNK_PARAMS:
        RESNETS:
          DEPTH: 50
          ######## resnext50-32x4d #######
          # GROUPS: 32
          # WIDTH_PER_GROUP: 4
          ######## resnext50-32x8d #######
          # GROUPS: 32
          # WIDTH_PER_GROUP: 8
          ######## resnext50-32x16d #######
          # GROUPS: 32
          # WIDTH_PER_GROUP: 16
    HEAD:
      PARAMS: [
        ['swav_head', {'dims': [2048, 2048, 128], 'use_bn': True, 'num_clusters': []}]
      ]
