{% set name = "classy_vision" %}
{% set version = "0.5.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/facebookresearch/ClassyVision/archive/v{{version}}.tar.gz

build:
  string: py{{py}}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pytorch >=1.3.1
    - torchvision >=0.4.2

test:
  imports:
    - classy_vision
  commands:
    - classy-project test_project

about:
  home: https://classyvision.ai
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An end-to-end PyTorch framework for image and video classification
  doc_url: https://classyvision.ai/
  dev_url: https://github.com/facebookresearch/ClassyVision/

extra:
  recipe-maintainers:
    - mannatsingh
    - vreis
    - aadcock
