# @package _global_
config:
  TEST_ONLY: True
  METERS:
    name: accuracy_list_meter
    accuracy_list_meter:
      topk_values: [1, 5]
      meter_names: ["1", "2", "3", "4"]
  HOOKS:
    TENSORBOARD_SETUP:
      # whether to use tensorboard for the visualization
      USE_TENSORBOARD: True
      # log directory for tensorboard events
      LOG_DIR: "logs"
      EXPERIMENT_LOG_DIR: "tensorboard"
      # flush logs every n minutes
      FLUSH_EVERY_N_MIN: 5
      # whether to log the model parameters to tensorboard
      LOG_PARAMS: False
      # whether to log the model parameters gradients to tensorboard
      LOG_PARAMS_GRADIENTS: False
      # if we want to log the model parameters every few iterations, set the iteration
      # frequency. -1 means the params will be logged only at the end of epochs.
      LOG_PARAMS_EVERY_N_ITERS: -1
  CHECKPOINT:
    DIR: "checkpoints/eval"
  DISTRIBUTED:
    NUM_PROC_PER_NODE: 1
  DATA:
    TRAIN:
      DATASET_NAMES: []
    TEST:
      DATA_SOURCES: [disk_folder]
      LABEL_SOURCES: [disk_folder]
      DATASET_NAMES: [imagenet1k_folder]
      DATA_PATHS: [/home/jan.olszewski/datasets/tiny-imagenet-200/val]
      BATCHSIZE_PER_REPLICA: 512
      TRANSFORMS:
        - name: Resize
          size: 256
          interpolation: 3
        - name: CenterCrop
          size: 224
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
  MODEL:
    FEATURE_EVAL_SETTINGS:
      EVAL_MODE_ON: True
      #FREEZE_TRUNK_ONLY: True
      FREEZE_TRUNK_AND_HEAD: True
      EVAL_TRUNK_AND_HEAD: True
      SHOULD_FLATTEN_FEATS: False
      LINEAR_EVAL_FEAT_POOL_OPS_MAP: [
        ["concatCLS4", ["Identity", []] ],
        ["lastCLS", ["Identity", []] ],
        ["concatCLS4", ["Identity", []] ],
        ["lastCLS", ["Identity", []] ],
      ]
    TRUNK: # S-16
      NAME: vision_transformer
      VISION_TRANSFORMERS:
        IMAGE_SIZE: 224
        PATCH_SIZE: 16
        HIDDEN_DIM: 384
        NUM_LAYERS: 12
        NUM_HEADS: 6
        MLP_DIM: 1536
        CLASSIFIER: token
        DROPOUT_RATE: 0
        ATTENTION_DROPOUT_RATE: 0
        QKV_BIAS: True
        DROP_PATH_RATE: 0.1 # stochastic depth dropout probability
    HEAD:
      PARAMS: [
        ["eval_mlp", {"in_channels": 1536, "dims": [1536, 200]}],
        ["eval_mlp", {"in_channels": 384, "dims": [384, 200]}],
        ["mlp", {"dims": [1536, 200]}],
        ["mlp", {"dims": [384, 200]}],
      ]
    WEIGHTS_INIT:
      # Use the teacher to perform the evaluation
      PARAMS_FILE: /home/jan.olszewski/git/vissl/checkpoints/linear/model_final_checkpoint_phase99.torch
  LOSS:
    name: cross_entropy_multiple_output_single_target